version: "3.8"
services:
  discordintelbot:
    build:
      context: ./DiscordIntelBot
      dockerfile: Dockerfile
    image: vxug-discordintelbot:swarm-1.6.2
    volumes:
      - type: bind
        source: ./DiscordIntelBot/Config
        target: /app/Config
    secrets:
      - source: discord_privsec-feed
        target: privsec-feed
        uid: '1000'
        gid: '101'
        mode: 0440
      - source: discord_govt-feed
        target: govt-feed
        uid: '1000'
        gid: '101'
        mode: 0440
      - source: discord_ransomware-feed
        target: ransomware-feed
        uid: '1000'
        gid: '101'
        mode: 0440
      - source: discord_status-feed
        target: status-feed
        uid: '1000'
        gid: '101'
        mode: 0440
      - source: discord_anssi-feed
        target: anssi-feed
        uid: '1000'
        gid: '101'
        mode: 0440
      - source: discord_rt-feed
        target: rt-feed
        uid: '1000'
        gid: '101'
        mode: 0440
      - source: discord_priv_privsec-feed
        target: priv_privsec-feed
        uid: '1000'
        gid: '101'
        mode: 0440
      - source: discord_priv_govt-feed
        target: priv_govt-feed
        uid: '1000'
        gid: '101'
        mode: 0440
      - source: discord_priv_ransomware-feed
        target: priv_ransomware-feed
        uid: '1000'
        gid: '101'
        mode: 0440
      - source: discord_priv_status-feed
        target: priv_status-feed
        uid: '1000'
        gid: '101'
        mode: 0440
      - source: discord_priv_anssi-feed
        target: priv_anssi-feed
        uid: '1000'
        gid: '101'
        mode: 0440
      - source: discord_priv_rt-feed
        target: priv_rt-feed
        uid: '1000'
        gid: '101'
        mode: 0440

  #telegramintelbot:
  #  build:
  #    context: ./TelegramIntelBot
  #    dockerfile: Dockerfile
  #  image: vxug-telegramintelbot:swarm-1.3.1
  #  volumes:
  #    - type: bind
  #      source: ./TelegramIntelBot
  #      target: /app
  #  secrets:
  #    - source: discord_telegram-feed
  #      target: telegram-feed
  #      uid: '1000'
  #      gid: '101'
  #      mode: 0440
  #    - source: telegram_api_hash
  #      target: api_hash
  #      uid: '1000'
  #      gid: '101'
  #      mode: 0440
  #    - source: telegram_api_id
  #      target: api_id
  #      uid: '1000'
  #      gid: '101'
  #      mode: 0440
secrets:
  telegram_api_hash:
    external: true
  telegram_api_id:
    external: true
  discord_privsec-feed:
    external: true
  discord_govt-feed:
    external: true
  discord_ransomware-feed:
    external: true
  discord_status-feed:
    external: true
  discord_anssi-feed:
    external: true
  discord_rt-feed:
    external: true
  discord_priv_privsec-feed:
    external: true
  discord_priv_govt-feed:
    external: true
  discord_priv_ransomware-feed:
    external: true
  discord_priv_status-feed:
    external: true
  discord_priv_anssi-feed:
    external: true
  discord_priv_rt-feed:
    external: true
